version: '3.3'

services:

  zammad:
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad

  zammad-backup:
    build:
      context: .
      dockerfile: containers/zammad-backup/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
      - backup-zammad:/var/tmp/zammad

  zammad-elasticsearch:
    build:
      context: .
      dockerfile: containers/zammad-elasticsearch/Dockerfile
    restart: always

  zammad-nginx:
    build:
      context: .
      dockerfile: containers/zammad-nginx/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "8102:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-postgresql:
    build:
      context: .
      dockerfile: containers/zammad-postgresql/Dockerfile
    restart: always

  zammad-railsserver:
    build:
      context: .
      dockerfile: containers/zammad-railsserver/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-scheduler:
    build:
      context: .
      dockerfile: containers/zammad-scheduler/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-websocket:
    build:
      context: .
      dockerfile: containers/zammad-websocket/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad

volumes:
  backup-zammad:
    driver: local
  data-zammad:
    driver: local
